guestbook/books/urls.py
from django.conf.urls import url, patterns

from . import views


urlpatterns = patterns("",
    url(
        regex=r'^$',
        view=views.BookListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^(?P<slug>[\w.@+-]+)/$',
        view=views.BookDetailView.as_view(),
        name='detail'
    ),
    url(
        regex=r'^~create/$',
        view=views.BookCreateView.as_view(),
        name='create'
    ),
    url(
        regex=r'^(?P<pk>\d+)/~update/$',
        view=views.BookUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<pk>\d+)/~delete/$',
        view=views.BookDeleteView.as_view(),
        name='delete'
    ),
)

guestbook/comments/urls.py
from django.conf.urls import url, patterns

from . import views


urlpatterns = patterns("",
    url(
        regex=r'^create/$',
        view=views.CommentCreateView.as_view(),
        name='create'
    ),
)

guestbook/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView
from django.contrib import admin


admin.autodiscover()

urlpatterns = patterns('',
    url(
        r'^$',
        RedirectView.as_view(url=reverse_lazy('books:list')),
        name='index'
    ),
    url(r'^login/$', 'django.contrib.auth.views.login', name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout_then_login', name='logout'),
    url(r'^books/', include('books.urls', namespace='books')),
    url(r'^comments/', include('comments.urls', namespace='comments')),

    url(r'^admin/', include(admin.site.urls)),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

guestbook/books/models.py
from django.conf import settings
from django.core.urlresolvers import reverse
from django.db import models
from autoslug import AutoSlugField
from django.db.models import QuerySet
from model_utils.managers import PassThroughManager


class BookQuerySet(QuerySet):
    def own(self, user):
        return self.filter(owner=user).order_by('-title')


class Book(models.Model):

    title = models.CharField('название', max_length=50)
    moderate = models.BooleanField('премодерация', default=True)
    slug = AutoSlugField(
        'метка книги',
        unique=True,
        populate_from= 'title'
    )

    owner = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='владелец'
    )

    objects = PassThroughManager.for_queryset_class(BookQuerySet)()

    def get_absolute_url(self):
        settings.AUTOSLUG_SLUGIFY_FUNCTION(self.owner)
        return reverse('books:detail', kwargs={'slug': self.slug})

    def __str__(self):
        return self.title

guestbook/comments/models.py
from django.conf import settings
from django.db import models
from django.db.models import Q, QuerySet
from model_utils.managers import PassThroughManager
from model_utils.models import TimeStampedModel


class CommentQuerySet(QuerySet):
    def public(self):
        return self.filter(Q(book__moderate=True, checked=True) | Q(book__moderate=False)).order_by('-created')


class Comment(TimeStampedModel):

    content = models.CharField('содержание', max_length=140)
    checked = models.BooleanField('проверено', default=False)

    book = models.ForeignKey(
        'books.Book',
        verbose_name='гостевая книга'
    )
    author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name='автор',
        null=True,
        blank=True
    )

    objects = PassThroughManager.for_queryset_class(CommentQuerySet)()

    def __str__(self):
        return self.content

guestbook/books/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.core.urlresolvers import reverse_lazy
from django.db.models import Prefetch
from django.views.generic import ListView, UpdateView, CreateView, DeleteView, DetailView
from braces.views import LoginRequiredMixin, SelectRelatedMixin, PrefetchRelatedMixin

from .models import Book
from comments.models import Comment


class BookListView(LoginRequiredMixin, SelectRelatedMixin, ListView):
    model = Book
    select_related = ('owner', )

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.own(self.request.user)


class BookDetailView(PrefetchRelatedMixin, DetailView):
    model = Book
    prefetch_related = (
        Prefetch('comment_set', queryset=Comment.objects.public().select_related('author')),
    )

class BookActionMixin(SuccessMessageMixin):

    model = Book
    fields = ('title', 'moderate')
    success_url = reverse_lazy('books:list')


class BookCreateView(BookActionMixin, LoginRequiredMixin, CreateView):
    success_message = 'Вы создали новую книгу'

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class BookUpdateView(BookActionMixin, LoginRequiredMixin, UpdateView):
    success_message = 'Вы изменили книгу'


class BookDeleteView(LoginRequiredMixin, DeleteView):
    model = Book
    success_url = reverse_lazy('books:list')

guestbook/comments/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.views.generic import CreateView

from .models import Comment


class CommentCreateView(SuccessMessageMixin, CreateView):
    model = Comment
    fields =  ('content', 'book')
    success_message = 'Вы добавили комментарий!'

    def form_valid(self, form):
        if self.request.user.is_authenticated():
            form.instance.author = self.request.user
        return super(CommentCreateView, self).form_valid(form)

    def get_success_url(self):
        return self.object.book.get_absolute_url()

guestbook/templates/base.html
{% load staticfiles %}<!doctype html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>{% block title %}Гостевая книга{% endblock title %}</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap-theme.min.css">
</head>
<body>

<nav class="navbar navbar-static-top navbar-inverse" role="navigation">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Гостевая книга</a>
        <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
                <li><p class="navbar-text">{{ user.get_username }}</p></li>
                <li><a href="{% url 'logout' %}">Выйти</a></li>
            {% else %}
                <li><a href="#authorization" data-toggle="modal">Войти</a></li>
            {% endif %}
        </ul>
    </div>
</nav>


<div class="container">
    {% if messages %}
        {% for message in messages %}
            <div class="alert {% if message.tags %}alert-{{ message.tags }}"{% endif %}>{{ message }}</div>
        {% endfor %}
    {% endif %}


    {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
    {% endblock content %}
</div>

{% if not user.is_authenticated %}
    <div id="authorization" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal"
                            aria-hidden="true">&times;</button>
                    <h4 class="modal-title">Войти</h4>
                </div>
                <div class="modal-body">
                    {% include "registration/_login_form.html" %}
                </div>
            </div>
        </div>
    </div>
{% endif %}

<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
<script src="//netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>
<script src="{% static 'js/project.js' %}"></script>
</body>
</html>

guestbook/templates/books/book_detail.html
{% extends 'base.html' %}

{% block title %}
    Оставтье комментарий в гостевой книге
{% endblock title %}

{% block content %}

    <h3>Комментарии гостевой книги "{{ book.title }}"</h3>

    <table class="table table-bordered table-striped">
        <tr>
            <th>Имя</th>
            <th>Текст</th>
            <th>Дата</th>
        </tr>
        {% for comment  in book.comment_set.all %}
            <tr>
                <td>{{ comment.author|default:"Аноним" }}</td>
                <td>{{ comment.content }}</td>
                <td>{{ comment.created|date:"DATETIME_FORMAT" }}</td>
            </tr>
        {% endfor %}
    </table>

    <div class="well">
        <h4>Новый комментарий</h4>

        <form action="{% url 'comments:create' %}" method="post" role="form">{% csrf_token %}
            <input type="text" name="book" class="hidden" value="{{ book.id }}">
            <div class="form-group">
                <textarea name="content" class="form-control" rows="3" placeholder="Текст комментария"></textarea>
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
        </form>
    </div>

{% endblock content %}

guestbook/templates/books/book_list.html
{% extends 'base.html' %}

{% block title %}
    Ваши гостевые книги
{% endblock title %}

{% block content %}

    <div class="jumbotron">
        <a href="#create-update" class="btn btn-primary btn-lg btn-block" data-url="{% url 'books:create' %}" role="button">
            Создать гостевую книгу
        </a>
    </div>

    <ul class="list-group">
        {% for book in book_list %}
            <li class="list-group-item">
                <a href="#delete" class="badge" data-url="{% url 'books:delete' pk=book.pk %}"><i
                        class="glyphicon glyphicon-remove"></i></a>
                <a href="#create-update" class="badge" data-url="{% url 'books:update' pk=book.pk %}"><i
                        class="glyphicon glyphicon-pencil"></i></a>
                <a href="{{ book.get_absolute_url }}" class="name">{{ book.title }}</a>
                {% if book.moderate %}
                    <span class="label label-warning">Модерация</span>
                {% endif %}
                <span class="label label-info">{{ book.get_absolute_url }}</span>
            </li>
        {% empty %}
            <h3 class="text-center">
                У Вас пока нет ни одной книги! Создайте её
            </h3>
        {% endfor %}
    </ul>


    <div id="create-update" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="#" method="post" role="form">{% csrf_token %}
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Гостевая книга</h4>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label for="title">Название</label>
                            <input name="title" id="title" type="text" class="form-control" required
                                   placeholder="Название">
                        </div>
                        <div class="checkbox">
                            <label><input name="moderate" type="checkbox" checked>Модерация</label>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div id="delete" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <form action="#" method="post" role="form">{% csrf_token %}
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                        <h4 class="modal-title">Удаление гостевой книги</h4>
                    </div>
                    <div class="modal-body">
                        <p>Вы уверены? Восстановить гостевую книгу будет невозможно</p>
                    </div>
                    <div class="modal-footer">
                        <button type="submit" class="btn btn-primary">Удалить</button>
                        <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                    </div>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

guestbook/templates/books/book_owner_detail.html
{% extends 'base.html' %}

{% block title %}
    Ваши гостевые книги
{% endblock title %}

{% block content %}

    <h3>Комментарии гостевой книги "{{ book.title }}"</h3>

    <form action="/" class="moderate" role="form">
        <table class="table table-bordered table-striped">
            <tr>
                <th>Имя</th>
                <th>Текст</th>
                <th>Дата</th>
                <th>Одобрено</th>
            </tr>
            {% for comment  in book.comment_set.all %}
                <tr>
                    <td>{{ comment.autor|default:"Аноним" }}</td>
                    <td>{{ comment.content }}</td>
                    <td>{{ comment.created|date:"DATETIME_FORMAT" }}</td>
                    <td>
                        <input name="id" type="text" class="hidden" value="id"/>
                        <input name="moderate" type="checkbox">
                    </td>
                </tr>

            {% endfor %}
        </table>

        <div class="form-group">
            <button type="submit" class="btn btn-primary">Сохранить</button>
            <button type="button" class="btn btn-success s-approve-all">Одобрить все</button>
        </div>
    </form>

{% endblock content %}